man(arthur).
man(anton).
man(alex).
man(artem).
man(andrey).
man(arseniy).
man(achilley).
man(albert).
man(athansins).

woman(anna).
woman(alena).
woman(anastasia).
woman(alina).
woman(alexandra).
woman(angelina).
woman(amalia).

child(artem,anna).
child(artem,arthur).
child(andrey,anna).
child(andrey,arthur).
child(alina,alena).
child(alina,anton).
child(arseniy,alena).
child(arseniy,anton).
child(alexandra,anastasia).
child(alexandra,alex).
child(achiley,anastasia).
child(achiley,alex).
child(amalia,anastasia).
child(amalia,alex).
child(albert,andrey).
child(albert,alina).
child(angelina,arseniy).
child(angelina,alexandra).
child(athansins,angelina).
child(athansins,albert).

grand_da(X,Y):-woman(X),child(X,Z),child(Z,Y).
grand_dats(X):-grand_da(X,Y).
